// <auto-generated />
using System;
using InstituteWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstituteWebAPI.Migrations
{
    [DbContext(typeof(RozhnInstituteDbContext))]
    [Migration("20260531204308_AddTerminalResultSnapshot")]
    partial class AddTerminalResultSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Admissions", b =>
                {
                    b.Property<Guid>("AdmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdmissionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("AdmittedClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DueDate")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeavingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdmissionID");

                    b.HasIndex("AdmittedClassID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.ClassStudents", b =>
                {
                    b.Property<Guid>("ClassStudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassStudentID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("StudentID");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Classes", b =>
                {
                    b.Property<Guid>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassID");

                    b.HasIndex("CourseID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Courses", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CourseStatus")
                        .HasColumnType("bit");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.CurrentClass", b =>
                {
                    b.Property<Guid>("CurrentClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SectionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrentClassID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SectionID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SlotID");

                    b.HasIndex("TeacherID");

                    b.HasIndex("TermID");

                    b.ToTable("CurrentClasses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.FeeDue", b =>
                {
                    b.Property<Guid>("FeeDueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FeeMonth")
                        .HasColumnType("date");

                    b.Property<int>("FeeType")
                        .HasColumnType("int");

                    b.Property<bool>("IsLateFeeWaived")
                        .HasColumnType("bit");

                    b.Property<decimal>("LateFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FeeDueId");

                    b.HasIndex("AdmissionId", "FeeType", "FeeMonth")
                        .IsUnique()
                        .HasFilter("[FeeMonth] IS NOT NULL");

                    b.ToTable("FeeDues");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.FeeSettings", b =>
                {
                    b.Property<Guid>("FeeSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdmissionFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CardFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LateFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeeSettingsId");

                    b.ToTable("FeeSettings");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.FeeType", b =>
                {
                    b.Property<Guid>("FeeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeeTypeID");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Guardian", b =>
                {
                    b.Property<Guid>("GuardianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GuardianID");

                    b.HasIndex("StudentID");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.MarkEditRequest", b =>
                {
                    b.Property<Guid>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("CurrentMarks")
                        .HasColumnType("real");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RequestedMarks")
                        .HasColumnType("real");

                    b.Property<string>("ReviewRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentMarkID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RequestID");

                    b.HasIndex("StudentMarkID");

                    b.HasIndex("TeacherID");

                    b.ToTable("MarkEditRequests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecipientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.PaymentDetail", b =>
                {
                    b.Property<Guid>("PaymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeeDueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentDetailId");

                    b.HasIndex("FeeDueId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.ResultApproval", b =>
                {
                    b.Property<Guid>("ApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApprovalID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("TermID", "CurrentClassID")
                        .IsUnique();

                    b.ToTable("ResultApprovals");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Scholarship", b =>
                {
                    b.Property<Guid>("ScholarshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ToMonth")
                        .HasColumnType("date");

                    b.HasKey("ScholarshipID");

                    b.HasIndex("AdmissionID");

                    b.HasIndex("StudentID");

                    b.ToTable("Scholarships");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Section", b =>
                {
                    b.Property<Guid>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SectionID");

                    b.HasIndex("TermID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Sessions", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SessionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Slots", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SessionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SlotID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SessionID");

                    b.HasIndex("TermID");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentAttendance", b =>
                {
                    b.Property<Guid>("StudentAttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarkedByTeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentAttendanceID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("MarkedByTeacherID");

                    b.HasIndex("StudentID");

                    b.HasIndex("AttendanceDate", "CurrentClassID", "StudentID")
                        .IsUnique();

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentFeeHistory", b =>
                {
                    b.Property<Guid>("FeeHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeeHistoryID");

                    b.HasIndex("CourseID");

                    b.HasIndex("AdmissionID", "EffectiveFrom");

                    b.ToTable("StudentFeeHistories");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentLeaveRequest", b =>
                {
                    b.Property<Guid>("StudentLeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LeavingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestedByTeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentLeaveRequestID");

                    b.HasIndex("AdmissionID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("RequestedByTeacherID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentLeaveRequests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMarks", b =>
                {
                    b.Property<Guid>("StudentMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalMarks")
                        .HasColumnType("real");

                    b.HasKey("StudentMarkID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermID");

                    b.HasIndex("TestID");

                    b.ToTable("StudentMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMonthlyResult", b =>
                {
                    b.Property<Guid>("StudentMonthlyResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermMonthID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalMarks")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentMonthlyResultID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermMonthID");

                    b.HasIndex("TermID", "CurrentClassID", "TermMonthID", "StudentID")
                        .IsUnique();

                    b.ToTable("StudentMonthlyResults");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Students", b =>
                {
                    b.Property<Guid>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherCnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<string>("StudentContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VillageID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentID");

                    b.HasIndex("VillageID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TeacherCourses", b =>
                {
                    b.Property<Guid>("TeacherCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CourseIsTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TeacherCourseID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeacherCourses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TeacherDailyAttendance", b =>
                {
                    b.Property<Guid>("TeacherDailyAttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarkedByUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScannedBarcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TeacherDailyAttendanceID");

                    b.HasIndex("TeacherID", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("TeacherDailyAttendances");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Teachers", b =>
                {
                    b.Property<Guid>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTeaching")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Term", b =>
                {
                    b.Property<Guid>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TermDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TermEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TermStart")
                        .HasColumnType("datetime2");

                    b.HasKey("TermID");

                    b.ToTable("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonthPassingMark", b =>
                {
                    b.Property<Guid>("TermMonthPassingMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PassingMarks")
                        .HasColumnType("real");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermMonthID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TermMonthPassingMarkID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("TermID");

                    b.ToTable("TermMonthPassingMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonths", b =>
                {
                    b.Property<Guid>("TermMonthID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TermMonth")
                        .HasColumnType("int");

                    b.HasKey("TermMonthID");

                    b.ToTable("TermMonths");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TerminalPassingMark", b =>
                {
                    b.Property<Guid>("TerminalPassingMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PassingMarks")
                        .HasColumnType("real");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TerminalPassingMarkID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("TermID", "CurrentClassID")
                        .IsUnique();

                    b.ToTable("TerminalPassingMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TerminalResult", b =>
                {
                    b.Property<Guid>("TerminalResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeMonth1")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeMonth2")
                        .HasColumnType("bit");

                    b.Property<float>("Month1ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<Guid?>("Month1TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Month1TotalMarks")
                        .HasColumnType("real");

                    b.Property<float>("Month2ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<Guid?>("Month2TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Month2TotalMarks")
                        .HasColumnType("real");

                    b.Property<float>("Month3ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<Guid>("Month3TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Month3TotalMarks")
                        .HasColumnType("real");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalMarksConsidered")
                        .HasColumnType("real");

                    b.Property<float>("TotalObtained")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TerminalResultID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermID", "CurrentClassID", "StudentID")
                        .IsUnique();

                    b.ToTable("TerminalResults");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TestType", b =>
                {
                    b.Property<Guid>("TestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestTypeID");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Tests", b =>
                {
                    b.Property<Guid>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermMonthID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalMarks")
                        .HasColumnType("real");

                    b.HasKey("TestID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("TermID");

                    b.HasIndex("TermMonthID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Village", b =>
                {
                    b.Property<Guid>("VillageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VillageID");

                    b.ToTable("Village");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Admissions", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Classes", "AdmittedClass")
                        .WithMany()
                        .HasForeignKey("AdmittedClassID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany("Admissions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany("Admissions")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmittedClass");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.ClassStudents", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany("ClassStudents")
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Classes", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.CurrentClass", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Classes", "Class")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionID");

                    b.HasOne("InstituteWebApp.Models.Domain.Sessions", "Session")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("SessionID");

                    b.HasOne("InstituteWebApp.Models.Domain.Slots", "Slot")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("SlotID");

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "Teacher")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("TeacherID");

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("TermID");

                    b.Navigation("Class");

                    b.Navigation("Section");

                    b.Navigation("Session");

                    b.Navigation("Slot");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.FeeDue", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Admissions", "Admission")
                        .WithMany("FeeDues")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Guardian", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.MarkEditRequest", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.StudentMarks", "StudentMark")
                        .WithMany()
                        .HasForeignKey("StudentMarkID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentMark");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Payment", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.PaymentDetail", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.FeeDue", "FeeDue")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("FeeDueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Payment", "Payment")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FeeDue");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.ResultApproval", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Scholarship", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Admissions", "Admission")
                        .WithMany("Scholarships")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Section", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Slots", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany("Slots")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Sessions", "Session")
                        .WithMany("Slots")
                        .HasForeignKey("SessionID");

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany("Slots")
                        .HasForeignKey("TermID");

                    b.Navigation("Course");

                    b.Navigation("Session");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentAttendance", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "MarkedByTeacher")
                        .WithMany()
                        .HasForeignKey("MarkedByTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("MarkedByTeacher");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentFeeHistory", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Admissions", "Admission")
                        .WithMany("FeeHistories")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentLeaveRequest", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Admissions", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "RequestedByTeacher")
                        .WithMany()
                        .HasForeignKey("RequestedByTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("CurrentClass");

                    b.Navigation("RequestedByTeacher");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMarks", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany("StudentMarks")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany("StudentMarks")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Tests", "Test")
                        .WithMany("StudentMarks")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Term");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMonthlyResult", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.TermMonths", "TermMonth")
                        .WithMany()
                        .HasForeignKey("TermMonthID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Student");

                    b.Navigation("Term");

                    b.Navigation("TermMonth");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Students", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Village", "Village")
                        .WithMany("Students")
                        .HasForeignKey("VillageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TeacherCourses", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TeacherDailyAttendance", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonthPassingMark", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TerminalPassingMark", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TerminalResult", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Tests", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany("Tests")
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", null)
                        .WithMany("Tests")
                        .HasForeignKey("TermID");

                    b.HasOne("InstituteWebApp.Models.Domain.TermMonths", "TermMonth")
                        .WithMany("Tests")
                        .HasForeignKey("TermMonthID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("TermMonth");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Admissions", b =>
                {
                    b.Navigation("FeeDues");

                    b.Navigation("FeeHistories");

                    b.Navigation("Scholarships");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Classes", b =>
                {
                    b.Navigation("CurrentClasses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Courses", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Classes");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.CurrentClass", b =>
                {
                    b.Navigation("ClassStudents");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.FeeDue", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Payment", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Sessions", b =>
                {
                    b.Navigation("CurrentClasses");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Slots", b =>
                {
                    b.Navigation("CurrentClasses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Students", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("ClassStudents");

                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Teachers", b =>
                {
                    b.Navigation("CurrentClasses");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Term", b =>
                {
                    b.Navigation("CurrentClasses");

                    b.Navigation("Slots");

                    b.Navigation("StudentMarks");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonths", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Tests", b =>
                {
                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Village", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
