// <auto-generated />
using System;
using InstituteWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstituteWebAPI.Migrations
{
    [DbContext(typeof(RozhnInstituteDbContext))]
    [Migration("20260208080724_PendingModelSync")]
    partial class PendingModelSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Admissions", b =>
                {
                    b.Property<Guid>("AdmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DueDate")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeavingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdmissionID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.ClassStudents", b =>
                {
                    b.Property<Guid>("ClassStudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassStudentID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("StudentID");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Classes", b =>
                {
                    b.Property<Guid>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassID");

                    b.HasIndex("CourseID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Courses", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CourseStatus")
                        .HasColumnType("bit");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.CurrentClass", b =>
                {
                    b.Property<Guid>("CurrentClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SectionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrentClassID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SectionID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SlotID");

                    b.HasIndex("TeacherID");

                    b.HasIndex("TermID");

                    b.ToTable("CurrentClasses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.FeeType", b =>
                {
                    b.Property<Guid>("FeeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeeTypeID");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Section", b =>
                {
                    b.Property<Guid>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Sessions", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SessionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Slots", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SessionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SlotID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SessionID");

                    b.HasIndex("TermID");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentAttendance", b =>
                {
                    b.Property<Guid>("StudentAttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarkedByTeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentAttendanceID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("MarkedByTeacherID");

                    b.HasIndex("StudentID");

                    b.HasIndex("AttendanceDate", "CurrentClassID", "StudentID")
                        .IsUnique();

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMarks", b =>
                {
                    b.Property<Guid>("StudentMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalMarks")
                        .HasColumnType("real");

                    b.HasKey("StudentMarkID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermID");

                    b.HasIndex("TestID");

                    b.ToTable("StudentMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMonthlyResult", b =>
                {
                    b.Property<Guid>("StudentMonthlyResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ObtainedMarks")
                        .HasColumnType("real");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermMonthID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalMarks")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentMonthlyResultID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermMonthID");

                    b.HasIndex("TermID", "CurrentClassID", "TermMonthID", "StudentID")
                        .IsUnique();

                    b.ToTable("StudentMonthlyResults");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Students", b =>
                {
                    b.Property<Guid>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherCnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<string>("StudentContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VillageID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentID");

                    b.HasIndex("VillageID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TeacherCourses", b =>
                {
                    b.Property<Guid>("TeacherCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CourseIsTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TeacherCourseID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeacherCourses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Teachers", b =>
                {
                    b.Property<Guid>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTeaching")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Term", b =>
                {
                    b.Property<Guid>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TermDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TermEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TermStart")
                        .HasColumnType("datetime2");

                    b.HasKey("TermID");

                    b.ToTable("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonthPassingMark", b =>
                {
                    b.Property<Guid>("TermMonthPassingMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PassingMarks")
                        .HasColumnType("real");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermMonthID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TermMonthPassingMarkID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("TermID");

                    b.ToTable("TermMonthPassingMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonths", b =>
                {
                    b.Property<Guid>("TermMonthID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TermMonth")
                        .HasColumnType("int");

                    b.HasKey("TermMonthID");

                    b.ToTable("TermMonths");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TerminalResult", b =>
                {
                    b.Property<Guid>("TerminalResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IncludeMonth1")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeMonth2")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Month1TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Month2TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Month3TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalMarksConsidered")
                        .HasColumnType("real");

                    b.Property<float>("TotalObtained")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TerminalResultID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermID", "CurrentClassID", "StudentID")
                        .IsUnique();

                    b.ToTable("TerminalResults");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Tests", b =>
                {
                    b.Property<Guid>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TermID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermMonthID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalMarks")
                        .HasColumnType("real");

                    b.HasKey("TestID");

                    b.HasIndex("CurrentClassID");

                    b.HasIndex("TermID");

                    b.HasIndex("TermMonthID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Village", b =>
                {
                    b.Property<Guid>("VillageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VillageID");

                    b.ToTable("Village");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Admissions", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany("Admissions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany("Admissions")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.ClassStudents", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany("ClassStudents")
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Classes", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.CurrentClass", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Classes", "Class")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionID");

                    b.HasOne("InstituteWebApp.Models.Domain.Sessions", "Session")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("SessionID");

                    b.HasOne("InstituteWebApp.Models.Domain.Slots", "Slot")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("SlotID");

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "Teacher")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("TeacherID");

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany("CurrentClasses")
                        .HasForeignKey("TermID");

                    b.Navigation("Class");

                    b.Navigation("Section");

                    b.Navigation("Session");

                    b.Navigation("Slot");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Slots", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany("Slots")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Sessions", "Session")
                        .WithMany("Slots")
                        .HasForeignKey("SessionID");

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany("Slots")
                        .HasForeignKey("TermID");

                    b.Navigation("Course");

                    b.Navigation("Session");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentAttendance", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "MarkedByTeacher")
                        .WithMany()
                        .HasForeignKey("MarkedByTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("MarkedByTeacher");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMarks", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany("StudentMarks")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany("StudentMarks")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Tests", "Test")
                        .WithMany("StudentMarks")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Term");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.StudentMonthlyResult", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.TermMonths", "TermMonth")
                        .WithMany()
                        .HasForeignKey("TermMonthID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Student");

                    b.Navigation("Term");

                    b.Navigation("TermMonth");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Students", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Village", "Village")
                        .WithMany("Students")
                        .HasForeignKey("VillageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TeacherCourses", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.Courses", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Teachers", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonthPassingMark", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TerminalResult", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany()
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Tests", b =>
                {
                    b.HasOne("InstituteWebApp.Models.Domain.CurrentClass", "CurrentClass")
                        .WithMany("Tests")
                        .HasForeignKey("CurrentClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstituteWebApp.Models.Domain.Term", null)
                        .WithMany("Tests")
                        .HasForeignKey("TermID");

                    b.HasOne("InstituteWebApp.Models.Domain.TermMonths", "TermMonth")
                        .WithMany("Tests")
                        .HasForeignKey("TermMonthID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClass");

                    b.Navigation("TermMonth");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Classes", b =>
                {
                    b.Navigation("CurrentClasses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Courses", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Classes");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.CurrentClass", b =>
                {
                    b.Navigation("ClassStudents");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Sessions", b =>
                {
                    b.Navigation("CurrentClasses");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Slots", b =>
                {
                    b.Navigation("CurrentClasses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Students", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("ClassStudents");

                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Teachers", b =>
                {
                    b.Navigation("CurrentClasses");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Term", b =>
                {
                    b.Navigation("CurrentClasses");

                    b.Navigation("Slots");

                    b.Navigation("StudentMarks");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.TermMonths", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Tests", b =>
                {
                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("InstituteWebApp.Models.Domain.Village", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
